### ISSUE TITLE
Doesn't work with PHP 5.3

### ISSUE THREAD

**Issue by pableu** [mschindler83/fints-hbci-php#1]
The composer.json says this package requires PHP >= 5.3.2, but it can't work at all with PHP 5.3. 

In `lib/Fhp/Segment/AbstractSegment.php`, you use the short array syntax which was only introduced in PHP 5.4. 

If this is the only PHP 5.3 compatibility issue, I'd recommend not using the short array syntax. If there are other issues, it's probably easier to just incrase the minimum required version to 5.4.x in composer.json.

**Comment by mschindler83** [comment]
Hi @pableu,
Thanks for pointing that out.
I've replaced the short array syntax with the valid BC one.
Please let me know if it works now.
Thanks!

**Comment by pableu** [comment]
Sweet, I was just about to make a pull request. Yeah, it work perfectly now, thanks!

**Comment by mschindler83** [comment]
You're welcome :)
Feel free to open Issues if you find some more.
