### ISSUE TITLE
Nord/LB Hannover / BLSK not working, Response with status code 403

### ISSUE THREAD

**Issue by dennobaby** [mschindler83/fints-hbci-php#112]
Hi,

i tested the API with a Nord-LB/BLSK account. 
I used the following FinTS-URL: 
`https://banking-ni3.s-fints-pt-ni.de`

I don't know if this url is correct, as i have no access to the mentioned list (https://www.hbci-zka.de/institute/institut_auswahl.htm).

Here is the output:

> denno@backup:~/hbci-test/vendor/mschindler83/fints-hbci-php/Samples$ php saldo.php
> PHP Fatal error:  Uncaught Fhp\Adapter\Exception\CurlException: Bad response with status code 403 in /home/denno/hbci-test/vendor/mschindler83/fints-hbci-php/lib/Fhp/Adapter/Curl.php:91
> Stack trace:
> 0 /home/denno/hbci-test/vendor/mschindler83/fints-hbci-php/lib/Fhp/Connection.php(36): Fhp\Adapter\Curl->send(Object(Fhp\Message\Message))
> 1 /home/denno/hbci-test/vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php(121): Fhp\Connection->send(Object(Fhp\Message\Message))
> 2 /home/denno/hbci-test/vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php(325): Fhp\Dialog\Dialog->sendMessage(Object(Fhp\Message\Message))
> 3 /home/denno/hbci-test/vendor/mschindler83/fints-hbci-php/lib/Fhp/FinTs.php(126): Fhp\Dialog\Dialog->syncDialog()
> 4 /home/denno/hbci-test/vendor/mschindler83/fints-hbci-php/Samples/saldo.php(27): Fhp\FinTs->getSEPAAccounts()
> 5 {main}
>   thrown in /home/denno/hbci-test/vendor/mschindler83/fints-hbci-php/lib/Fhp/Adapter/Curl.php on line 91

**Comment by ickbinhier** [comment]
try this url: https://banking-li1.s-fints-pt-li.de/fints30

**Comment by dennobaby** [comment]
Nice! Thank you very much! May i ask where you found this url? Do you have access to the hbci-zka-list?

**Comment by ickbinhier** [comment]
https://github.com/willuhn/hbci4java/blob/master/src/blz.properties

i have no access to the hbci-zka-list.

**Comment by dennobaby** [comment]
Thank you very much!
