### ISSUE TITLE
Can't connect to Deutsche Bank

### ISSUE THREAD

**Issue by larsgrau** [mschindler83/fints-hbci-php#12]
Great gist! 

I believe my problem is related to my particular bank. I know that the URL is 
https://fints.deutsche-bank.de and the username is made up of 3 components: the 3-digit subsidiary id ("Filialnummer"), the 7-digit account number and the 2-digit subaccount number.
However, I can't establish a connection. 

Using your sample code here's what I get:

`Fatal error: Uncaught exception 'Fhp\Adapter\Exception\CurlException' with message 'Failed connection to https://fints.deutsche-bank.de/' in /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Adapter/Curl.php:80 Stack trace: #0 /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Connection.php(36): Fhp\Adapter\Curl->send(Object(Fhp\Message\Message)) #1 /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php(121): Fhp\Connection->send(Object(Fhp\Message\Message)) #2 /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php(325): Fhp\Dialog\Dialog->sendMessage(Object(Fhp\Message\Message)) #3 /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/FinTs.php(126): Fhp\Dialog\Dialog->syncDialog() #4 /.../test/account-statement.php(21): Fhp\FinTs->getSEPAAccounts() #5 {main} thrown in /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Adapter/Curl.php on line 80`

Any idea? Thanks!

**Comment by larsgrau** [comment]
Ay, got it, never mind

**Comment by dsentker** [comment]
I am facing the same problem. Do you have a solution?
I've written a custom CURL adapter (which sets CURLOPT_SSL_VERIFYHOST to 0), but i am sure there is a better solution.

**Comment by michabbb** [comment]
@larsgrau can you please tell us, what was the problem and how do you solved it? Thanks!
