### ISSUE TITLE
Transaction-ID missing

### ISSUE THREAD

**Issue by Jimmy-and-Jonny** [mschindler83/fints-hbci-php#123]
I sometimes have transactions with the same date, amount and purpose in my bank account, so I need a unique transactionID to avoid duplicates! Is there such an ID?

**Comment by ampaze** [comment]
The order per day is the implicit id. You have to generate a unique id yourself.

**Comment by Jimmy-and-Jonny** [comment]
If there are two identical transfers on the same day, I can't generate a unique id from "order per day".

**Comment by ampaze** [comment]
The transfers/statements are sent from the server in a certain order, and will always be in this same order for that day. So you have to use the position in the list and the date for your unique id.

**Comment by Jimmy-and-Jonny** [comment]
Ok, thanks!
