### ISSUE TITLE
Uncaught Exception: Could not determine system id

### ISSUE THREAD

**Issue by larsgrau** [mschindler83/fints-hbci-php#21]
I'm trying to connect to Deutsche Kreditbank Berlin (DKB) AG which is stated as compatible in your [compatibility.md](https://github.com/mschindler83/fints-hbci-php/blob/master/COMPATIBILITY.md)

According to [DKB website](https://www.dkb.de/DkbTransactionBanking/content/security/UserInfo/UserIdInfo.xhtml) the host address is `banking-dkb.s-fints-pt-dkb.de/fints30` (Port 443).

As far as I understand, the connection is established, but I do not understand what the error is actually telling me

Can you help?

**Comment by larsgrau** [comment]
Update –  I believe this relates to DKB-specific parameters / login parameters

`Fatal error: Uncaught Fhp\Adapter\Exception\CurlException: Failed connection to banking-dkb.s-fints-pt-dkb.de/fints30 in /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Adapter/Curl.php:80 Stack trace: #0 /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Connection.php(36): Fhp\Adapter\Curl->send(Object(Fhp\Message\Message)) #1 /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php(121): Fhp\Connection->send(Object(Fhp\Message\Message)) #2 /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php(325): Fhp\Dialog\Dialog->sendMessage(Object(Fhp\Message\Message)) #3 /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/FinTs.php(126): Fhp\Dialog\Dialog->syncDialog() #4 /.../app/controllers/BankingController.php(63): Fhp\FinTs->getSEPAAccounts() #5 /.../app/core/App.php(37): BankingController->accounts() #6 /... in /.../vendor/mschindler83/fints-hbci-php/lib/Fhp/Adapter/Curl.php on line 80`

**Comment by MrCrankHank** [comment]
Hm, are you sure, the server you're on has internet access? 

Further please try it with **https://**banking-dkb.s-fints-pt-dkb.de/fints30

I tested the library with the DKB and didn't encounter any issues.

**Comment by larsgrau** [comment]
Thanks for your feedback - I use exactly the URL (incl. https), and I am sure I have a working internet connection. Although I haven't got it working yet, I'll close the issue because I believe the connection error is not related to this library.
