### ISSUE TITLE
Verarbeitung Login/Benutzername fehlerhaft

### ISSUE THREAD

**Issue by Michamicha** [mschindler83/fints-hbci-php#3]
Hallo,

wenn der Loginname/Benutzername eine Emailadresse ist, führt das "@" Zeichen darin zu einem Fehler. Es muss durch "?@" ersetzt werden, bevor die Message zum Bankserver geschickt wird.

Wirklich grossen Respekt, die Library ist eine ausserordentlich gute Leistung!

Vielen Dank!

Micha

**Comment by mschindler83** [comment]
Hi @Michamicha 
Tanks for reporting. I will have a look at it as soon as possible.

**Comment by mschindler83** [comment]
@Michamicha Would be nice if you could check if this commit fixes now the issue. Thanks a lot!

**Comment by Michamicha** [comment]
working fine! (tested with emailaddress as loginname)

**Comment by mschindler83** [comment]
Perfect. Thanks a lot.
