### ISSUE TITLE
When customer have more than one account in the bank, data from first account is rewriting with data from second

### ISSUE THREAD

**Issue by mcprotector** [mschindler83/fints-hbci-php#30]
When customer have more than one account in the bank and construction for getting accounts information is
`$accounts = $fints->getSEPAAccounts();`
`foreach ($accounts as $account) {`
then data from first account is rewriting with data from second.

Issue is in a string (lib/Fhp/FinTS.php)
`$masterArray += $r->getStatementOfAccountArray();`
For correct work must be 
`$masterArray = array_merge($masterArray,$r->getStatementOfAccountArray());`

**Comment by MrCrankHank** [comment]
Could you submit a pull request for codes changes?

**Comment by mcprotector** [comment]
MrCrankHank, I don't known how to do it. +) Can you help me?

**Comment by MrCrankHank** [comment]
There is a lot of documentation out there, e.g.: 

[https://gist.github.com/Chaser324/ce0505fbed06b947d962](url)

**Comment by mschindler83** [comment]
Hi @mcprotector,

I don't get the problem here.
What has traversing over the accounts to do with fetching the bank statements?
Nethertheless when calling getStatementOfAccount() the $masterArray will get newly initiated on each call to this method. So it can not mix up with data from another account.

Maybe you can again explain in greater detail what the issue exactly is? Would be very good!

But still,... your suggestion to change += to array_merge is somehow valid. :)
I just don't see the issue.

**Comment by mcprotector** [comment]
Hello, Markus!

Maybe the problem is not because we have two accounts in one Bank. This relation i can't to confirm.
But this
`$masterArray += $r->getStatementOfAccountArray();`
rewrite masterArray elements by keys.
If i get in the first step 
`$r->getStatementOfAccountArray();`
as 
`array(0 => 0, 1 => 1, 2 => 2)`, 
and in the second step as 
`array(0 => 10, 1 => 11)`,
in result i get 
`array(0 => 10, 1 => 11, 2 => 2)`.
And two elements from first step is lost. In my case it happened.
Problem was happened with Cronkbank, two accounts and access by one pint/tan.
[Array-Operatoren](http://php.net/manual/de/language.operators.array.php)

**Comment by mschindler83** [comment]
Okay thanks. Now I understand :)

**Comment by mschindler83** [comment]
PR #33 is mergend with master

**Comment by mcprotector** [comment]
I have found one more problem. +)
Transactions of a day may be splited to pages. Every page is as new array with dates as keys  (e.g. 2017-01-10). When used += or array_merge, same day is replaced with new day array. New correct code is
```
foreach ($responses as $r) {
            $statementOfAccount = $r->getStatementOfAccountArray();
            foreach ($statementOfAccount as $day=>$info){
                if(isset($masterArray[$day])){
                    $masterArray[$day]['transactions'] = array_merge($masterArray[$day]['transactions'],$info['transactions']);
                } else {
                    $masterArray[$day] = $info;
                }
            }
        } 
```

**Comment by ekarakashi** [comment]
NOT OK

**Comment by mcprotector** [comment]
I was trying to use array_merge_recursive. No result.

**Comment by mschindler83** [comment]
I see. Yes, array_merge_recursive will not help here.
I've a solution. I will create a PR for this.
@mcprotector maybe you can then test again with the new PR and tell me if it works.

**Comment by mschindler83** [comment]
@mcprotector 
Can you please check if it works with this [branch](/mschindler83/fints-hbci-php/tree/bugfix/statement-parsing)?

**Comment by mcprotector** [comment]
I'll try to check as soon as the time. Some files in my copy of fints-hbci-php is changed for getting additional data (not errors or troubles). I must replace my copy with your new commit. It takes time. +))

**Comment by mschindler83** [comment]
I'm pretty sure that the PR fixed the issue.
Closing.
