### ISSUE TITLE
Commerzbank Compatibility

### ISSUE THREAD

**Issue by TenMediaBln** [mschindler83/fints-hbci-php#65]
Hi!

First, thank you for providing such a great package! It looks stable and solid.

Second, how did Commerzbank make it one the compatibility list? It seems they don't support any access with Pin/Tan and they don't provide any Pin/Tan-Url @ https://www.hbci-zka.de/institute/institut_auswahl.htm. Do I miss something here or is Commerzbank not accessible?

I tried accessing Commerzbank anyway using hbci.commerbank.de and fints.commerzbank.de since some users said Commerzbank would just not offer access officially, but I had no success. Afterwards I talked to their customer service, confirming that they don't provide Pin/Tan Access. 

Does anyone have different experience? 

Thank you!

**Comment by neuni** [comment]
Hi,

some branch banks of Commerzbank support FinTS, other not.
For example Commerzbank Gütersloh (BLZ 47840065) supports FinTS, but Commerzbank Hamburg not. Our contact at Commerzbank Hamburg did his best to activate FinTS for one of our clients account, but is was not possible.

**Comment by mansouryaacoubi** [comment]
Unfortunately it seems like no branch office of Commerzbank supports FinTS.
This is the answer I got from the Commerzbank tech support:

> Sehr geehrter Herr Yaacoubi,
> 
> vielen Dank für Ihre Anfrage vom 8. November 2017, 11:21 Uhr.
> 
> Bitte beachten Sie bei der Einrichtung Ihrer Konten, dass der Zugang über PIN/TAN-Internet (Screenscraping) von Ihrer Finanzsoftware zur Verfügung gestellt, von der Commerzbank aber nicht offiziell angeboten und somit nicht unterstützt wird. Commerzbank-Konten können über eine Finanzsoftware nur über das HBCI-Verfahren verwaltet werden.
> 
> Ihre Anregung haben wir an die Entwicklung weitergeleitet. Ob und wann diese Änderung umgesetzt wird, können wir Ihnen zum jetzigen Zeitpunkt nicht sagen.
> 
> Ausführliche Informationen zu HBCI haben wir für Sie unter www.commerzbank.de/hbci zusammengestellt.
> 
> Für weitere Rückfragen kontaktieren Sie uns gerne 24 Stunden täglich unter der unten angegebenen Telefonnummer.
> 
> Wir wünschen Ihnen einen schönen Tag.

I asked whether it will be possible in future to use other safety methods like PIN/TAN and this is what they answered.

**Comment by mschindler83** [comment]
I don't think that they will implement this feature in the near future.
IMO they will wait until it is clear on how the PSD2 will affect the FinTS protocol.
It can (most likely) happen, that FinTS will die anyway in the next one or two year.
