### ISSUE TITLE
Only getting limited Number of Statements

### ISSUE THREAD

**Issue by Houbsi** [mschindler83/fints-hbci-php#74]
Hi,
it could be that the bank is not providing more statements over the FINTS/HBCI link. But i can't find any information anywhere about this "limitation".

BBBank (VR-Bank Verbund) gives only 60 statements?? Is there any more information about this kind of limitations??

**Comment by mschindler83** [comment]
Hi @Houbsi ,
As far as I know the limitation is mostly a time limit.
So I think the most common restriction of banks is to deliver back transactions from the last 3 months.

Someone correct my, if I'm wrong :)

**Comment by movabo** [comment]
In my case (also BBBank) i can just see the last 3 months.
This is pretty sure a restriction by the bank, as the online interface provided by the bank also doesn't show any more than the last three months. Even if i change the timespan accordingly.
