### ISSUE TITLE
Install with no Composer?

### ISSUE THREAD

**Issue by csskoeln** [mschindler83/fints-hbci-php#78]
Hello,

how can I use the FinTS HBCI PHP without composer?

**Comment by movabo** [comment]
I guess you need to install all dependencies on your own.
Here is how you can do that: https://stackoverflow.com/a/40545971
But i would recommend you just using composer. ;)

**Comment by csskoeln** [comment]
Hello,
thank you for the information.

Then I must probably still use the composer.

* Closed *
